[programs.localnet]
raffle = "2T49vgEJQFkkwR6nSNK7PuXyDEHnB7ctQ66NufFkbi88"
[programs.devnet]
raffle = "2T49vgEJQFkkwR6nSNK7PuXyDEHnB7ctQ66NufFkbi88"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/wstar/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
